# Generated by Django 4.0.3 on 2022-05-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_options_story_slug_alter_story_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='content_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='slug_az',
            field=models.SlugField(editable=False, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='slug_en',
            field=models.SlugField(editable=False, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_az',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_en',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(editable=False, max_length=70),
        ),
    ]
